version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/Native"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      backend:
        patterns:
          - "*"
    ignore:
      - dependency-name: "nucleation"
      - dependency-name: "schematic-mesher"

  - package-ecosystem: "cargo"
    directory: "/App/src-tauri"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      tauri:
        patterns:
          - "*"
    ignore:
      - dependency-name: "nucleation"

  - package-ecosystem: "npm"
    directory: "/App"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      frontend:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
