import { defineConfig, lazyPlugins } from "vite-plus"
import react from "@vitejs/plugin-react"
import tailwindcss from "@tailwindcss/vite"

export default defineConfig({
  fmt: {
    semi: false,
  },
  lint: {
    plugins: [
      "unicorn",
      "typescript",
      "oxc",
      "react",
      "import",
      "vitest",
      "jsx-a11y",
      "promise",
      "node",
      "jsdoc",
    ],
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    settings: {
      react: {
        version: "19.2.0",
      },
    },
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",

      // --- Core ESLint (Correctness & Best Practices) ---
      "accessor-pairs": "warn",
      "array-callback-return": "warn",
      "default-case-last": "warn",
      "default-param-last": "warn",
      eqeqeq: "warn",
      "guard-for-in": "warn",
      "logical-assignment-operators": "warn",
      "no-alert": "warn",
      "no-array-constructor": "warn",
      "no-case-declarations": "warn",
      "no-duplicate-imports": "warn",
      "no-else-return": "warn",
      "no-empty": "warn",
      "no-extend-native": "warn",
      "no-lone-blocks": "warn",
      "no-lonely-if": "warn",
      "no-new-func": "warn",
      "no-new-wrappers": "warn",
      "no-proto": "warn",
      "no-return-assign": "warn",
      "no-self-compare": "warn",
      "no-sequences": "warn",
      "no-template-curly-in-string": "warn",
      "no-throw-literal": "warn",
      "no-unneeded-ternary": "warn",
      "no-unreachable-loop": "warn",
      "no-useless-assignment": "warn",
      "no-useless-call": "warn",
      "no-useless-computed-key": "warn",
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-return": "warn",
      "no-var": "warn",
      "object-shorthand": "warn",
      "operator-assignment": "warn",
      "prefer-arrow-callback": "warn",
      "prefer-const": "warn",
      "prefer-exponentiation-operator": "warn",
      "prefer-numeric-literals": "warn",
      "prefer-object-has-own": "warn",
      "prefer-object-spread": "warn",
      "prefer-rest-params": "warn",
      "prefer-spread": "warn",
      "prefer-template": "warn",

      // --- React & Accessibility ---
      "react/react-in-jsx-scope": "off",
      "react/set-state-in-effect": "off",
      "jsx-a11y/prefer-tag-over-role": "off",
      "react/hook-use-state": "warn",
      "react/iframe-missing-sandbox": "warn",
      "react/jsx-boolean-value": "warn",
      "react/jsx-curly-brace-presence": "warn",
      "react/jsx-fragments": "warn",
      "react/jsx-no-comment-textnodes": "warn",
      "react/jsx-no-script-url": "warn",
      "react/jsx-no-target-blank": "warn",
      "react/jsx-no-useless-fragment": "warn",
      "react/jsx-pascal-case": "warn",
      "react/no-array-index-key": "warn",
      "react/no-children-prop": "warn",
      "react/no-danger": "warn",
      "react/no-unescaped-entities": "warn",
      "react/no-unknown-property": "warn",
      "react/no-unstable-nested-components": "warn",
      "react/rules-of-hooks": "warn",
      "react/self-closing-comp": "warn",
      "react/style-prop-object": "warn",
      "react/void-dom-elements-no-children": "warn",

      // --- TypeScript ---
      "typescript/adjacent-overload-signatures": "warn",
      "typescript/ban-tslint-comment": "warn",
      "typescript/consistent-type-exports": "warn",
      "typescript/no-confusing-non-null-assertion": "warn",
      "typescript/no-deprecated": "warn",
      "typescript/no-dynamic-delete": "warn",
      "typescript/no-empty-object-type": "warn",
      "typescript/no-extraneous-class": "warn",
      "typescript/no-misused-promises": "warn",
      "typescript/no-mixed-enums": "warn",
      "typescript/no-namespace": "warn",
      "typescript/no-non-null-asserted-nullish-coalescing": "warn",
      "typescript/no-require-imports": "warn",
      "typescript/no-unnecessary-template-expression": "warn",
      "typescript/no-unnecessary-type-arguments": "warn",
      "typescript/no-unnecessary-type-assertion": "warn",
      "typescript/no-unnecessary-type-constraint": "warn",
      "typescript/no-unnecessary-type-parameters": "warn",
      "typescript/no-unsafe-enum-comparison": "warn",
      "typescript/no-unsafe-function-type": "warn",
      "typescript/no-var-requires": "warn",
      "typescript/prefer-enum-initializers": "warn",
      "typescript/prefer-find": "warn",
      "typescript/prefer-for-of": "warn",
      "typescript/prefer-function-type": "warn",
      "typescript/prefer-includes": "warn",
      "typescript/prefer-literal-enum-member": "warn",
      "typescript/prefer-optional-chain": "warn",
      "typescript/prefer-promise-reject-errors": "warn",
      "typescript/prefer-reduce-type-parameter": "warn",
      "typescript/prefer-return-this-type": "warn",
      "typescript/prefer-string-starts-ends-with": "warn",
      "typescript/prefer-ts-expect-error": "warn",
      "typescript/related-getter-setter-pairs": "warn",
      "typescript/restrict-plus-operands": "warn",
      "typescript/switch-exhaustiveness-check": "warn",
      "typescript/unified-signatures": "warn",
      "typescript/use-unknown-in-catch-callback-variable": "warn",

      // --- Unicorn (Modern Idioms & Safety) ---
      "unicorn/consistent-empty-array-spread": "warn",
      "unicorn/consistent-existence-index-check": "warn",
      "unicorn/custom-error-definition": "warn",
      "unicorn/error-message": "warn",
      "unicorn/escape-case": "warn",
      "unicorn/no-abusive-eslint-disable": "warn",
      "unicorn/no-accessor-recursion": "warn",
      "unicorn/no-array-fill-with-reference-type": "warn",
      "unicorn/no-array-for-each": "warn",
      "unicorn/no-array-method-this-argument": "warn",
      "unicorn/no-confusing-array-with": "warn",
      "unicorn/no-instanceof-array": "warn",
      "unicorn/no-instanceof-builtins": "warn",
      "unicorn/no-lonely-if": "warn",
      "unicorn/no-magic-array-flat-depth": "warn",
      "unicorn/no-negation-in-equality-check": "warn",
      "unicorn/no-new-buffer": "warn",
      "unicorn/no-object-as-default-parameter": "warn",
      "unicorn/no-static-only-class": "warn",
      "unicorn/no-this-assignment": "warn",
      "unicorn/no-typeof-undefined": "warn",
      "unicorn/no-unnecessary-array-flat-depth": "warn",
      "unicorn/no-unnecessary-array-splice-count": "warn",
      "unicorn/no-unnecessary-slice-end": "warn",
      "unicorn/no-unreadable-array-destructuring": "warn",
      "unicorn/no-unreadable-iife": "warn",
      "unicorn/no-useless-collection-argument": "warn",
      "unicorn/no-useless-iterator-to-array": "warn",
      "unicorn/no-useless-promise-resolve-reject": "warn",
      "unicorn/no-useless-switch-case": "warn",
      "unicorn/no-useless-undefined": "warn",
      "unicorn/no-zero-fractions": "warn",
      "unicorn/prefer-array-flat": "warn",
      "unicorn/prefer-array-flat-map": "warn",
      "unicorn/prefer-array-index-of": "warn",
      "unicorn/prefer-array-some": "warn",
      "unicorn/prefer-blob-reading-methods": "warn",
      "unicorn/prefer-code-point": "warn",
      "unicorn/prefer-date-now": "warn",
      "unicorn/prefer-default-parameters": "warn",
      "unicorn/prefer-dom-node-append": "warn",
      "unicorn/prefer-dom-node-dataset": "warn",
      "unicorn/prefer-dom-node-remove": "warn",
      "unicorn/prefer-dom-node-text-content": "warn",
      "unicorn/prefer-event-target": "warn",
      "unicorn/prefer-export-from": "warn",
      "unicorn/prefer-includes": "warn",
      "unicorn/prefer-keyboard-event-key": "warn",
      "unicorn/prefer-logical-operator-over-ternary": "warn",
      "unicorn/prefer-math-min-max": "warn",
      "unicorn/prefer-math-trunc": "warn",
      "unicorn/prefer-modern-dom-apis": "warn",
      "unicorn/prefer-modern-math-apis": "warn",
      "unicorn/prefer-native-coercion-functions": "warn",
      "unicorn/prefer-negative-index": "warn",
      "unicorn/prefer-node-protocol": "warn",
      "unicorn/prefer-object-from-entries": "warn",
      "unicorn/prefer-optional-catch-binding": "warn",
      "unicorn/prefer-prototype-methods": "warn",
      "unicorn/prefer-reflect-apply": "warn",
      "unicorn/prefer-regexp-test": "warn",
      "unicorn/prefer-response-static-json": "warn",
      "unicorn/prefer-set-has": "warn",
      "unicorn/prefer-single-call": "warn",
      "unicorn/prefer-spread": "warn",
      "unicorn/prefer-string-slice": "warn",
      "unicorn/prefer-string-trim-start-end": "warn",
      "unicorn/prefer-structured-clone": "warn",
      "unicorn/require-array-join-separator": "warn",
      "unicorn/require-number-to-fixed-digits-argument": "warn",
      "unicorn/text-encoding-identifier-case": "warn",
      "unicorn/throw-new-error": "warn",

      // --- Promise ---
      "promise/catch-or-return": "warn",
      "promise/no-multiple-resolved": "warn",
      "promise/no-nesting": "warn",
      "promise/no-promise-in-callback": "warn",
      "promise/no-return-in-finally": "warn",
      "promise/no-return-wrap": "warn",
      "promise/prefer-catch": "warn",
      "promise/spec-only": "warn",

      // --- Node ---
      "node/global-require": "warn",
      "node/handle-callback-err": "warn",
      "node/no-exports-assign": "warn",
      "node/no-new-require": "warn",
      "node/no-path-concat": "warn",

      // --- Vitest ---
      "vitest/no-commented-out-tests": "warn",
      "vitest/no-disabled-tests": "warn",
      "vitest/no-duplicate-hooks": "warn",
      "vitest/no-focused-tests": "warn",
      "vitest/no-identical-title": "warn",
      "vitest/no-test-return-statement": "warn",
      "vitest/prefer-comparison-matcher": "warn",
      "vitest/prefer-equality-matcher": "warn",
      "vitest/prefer-hooks-in-order": "warn",
      "vitest/prefer-hooks-on-top": "warn",
      "vitest/prefer-strict-equal": "warn",
      "vitest/prefer-to-be": "warn",
      "vitest/prefer-to-contain": "warn",
      "vitest/prefer-to-have-length": "warn",
      "vitest/valid-expect": "warn",
      "vitest/valid-title": "warn",

      // --- Import ---
      "import/first": "warn",
      "import/no-amd": "warn",
      "import/no-cycle": "warn",
      "import/no-duplicates": "warn",
      "import/no-empty-named-blocks": "warn",
      "import/no-mutable-exports": "warn",
      "import/no-self-import": "warn",
      "import/no-webpack-loader-syntax": "warn",

      // --- Oxc ---
      "oxc/approx-constant": "warn",
      "oxc/bad-bitwise-operator": "warn",
      "oxc/branches-sharing-code": "warn",
      "oxc/misrefactored-assign-op": "warn",
      "oxc/no-accumulating-spread": "warn",
      "oxc/no-barrel-file": "warn",
      "oxc/no-const-enum": "warn",
      "oxc/no-map-spread": "warn",
    },
    overrides: [
      {
        files: ["**/*.test.mjs"],
        rules: {
          "typescript/restrict-template-expressions": "off",
        },
      },
    ],
    options: { typeAware: true, typeCheck: true },
  },
  plugins: lazyPlugins(() => [tailwindcss(), react()]),
  clearScreen: false,
  server: {
    port: 1420,
    strictPort: true,
    // Rust owns these files; watching loaded DLLs fails with EBUSY on Windows.
    watch: { ignored: ["**/src-tauri/**"] },
  },
  build: { target: "es2022", reportCompressedSize: false },
})
